CREATE TABLE raw_car_sales_transactions (
    Car_ID NVARCHAR(255),
    Transaction_Date NVARCHAR(50),
    Customer_Name NVARCHAR(255),
    Gender NVARCHAR(50),
    Annual_Income INT,
    Dealer_Name NVARCHAR(255),
    Car_Brand NVARCHAR(255),
    Car_Model NVARCHAR(255),
    Engine_Type NVARCHAR(255),
    Transmission_Type NVARCHAR(50),
    Car_Color NVARCHAR(50),
    Price_USD INT,
    Dealer_No NVARCHAR(50),
    Body_Style NVARCHAR(100),
    Phone_Number BIGINT,
    Dealer_Region NVARCHAR(100),
    Tanggal_Ingesti_Bronze DATETIME DEFAULT GETDATE(),
    Nama_File_Sumber NVARCHAR(255)
);
