CREATE TABLE raw_car_sales_transactions (
    car_id NVARCHAR(255),
    transaction_date NVARCHAR(50),
    customer_name NVARCHAR(255),
    gender NVARCHAR(50),
    annual_income INT,
    dealer_name NVARCHAR(255),
    car_brand NVARCHAR(255),
    car_model NVARCHAR(255),
    engine_type NVARCHAR(255),
    transmission_type NVARCHAR(50),
    car_color NVARCHAR(50),
    price_usd INT,
    dealer_no NVARCHAR(50),
    body_style NVARCHAR(100),
    phone_number BIGINT,
    dealer_region NVARCHAR(100),
    tanggal_ingesti_bronze DATETIME DEFAULT GETDATE(),
    nama_file_sumber NVARCHAR(255)
);
